#!/usr/bin/env bash
# PiJam
# Integrates fullpagedashboard-client into Raspbian
# Written by Tailor Vijay
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

curl -sL https://deb.nodesource.com/setup_10.x | bash -

#echo "This is an example module, install and set up what you need here!"
#echo "$PIJAM_VAR"
apt-get update
apt-get upgrade
apt-get dist-upgrade
apt-get clean
apt-get install screen
apt-get install unclutter
rpi-update

# Workaround for bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917633
apt-get -y --force-yes install udisks2 || true
sed -i 's/udevadm trigger --subsystem-match=block --action=change/udevadm trigger --subsystem-match=block --action=change || true/g' /var/lib/dpkg/info/udisks2.postinst
apt-get -y --force-yes install -f

apt-get -y --force-yes install screen pcmanfm git libgconf-2-4 gvfs
apt-get -y --force-yes install nodejs
#npm install electron@3.0.13 -g --arch=armv7l --platform=linux --unsafe-perm=true --allow-root
# get rid of the settings wizard on desktop startup:
rm /etc/xdg/autostart/piwiz.desktop
cp /home/pi/Pictures/lxde-desktop-background-fullpageos-logo-blackbg-1920x1080.png /usr/share/plymouth/themes/pix/splash.png

sudo -u pi mkdir -p /home/pi/electron
pushd /home/pi/electron
    gitclone PIJAM_FULLPAGEOS_DASHBOARD_CLIENT_REPO fullpagedashboard-client
    gitclone PIJAM_FULLPAGEOS_EXPERIMENAL_SHELL_SCRIPTS_REPO fullpageos-experimental-shell-scripts
    pushd fullpagedashboard-client
        sudo -u pi npm install
    popd
popd

# Unpack root at the end, so files are modified before
unpack /filesystem/root /